services:
  _defaults:
    autowire: true
    autoconfigure: true

  Gadget\:
    resource: '../../src/'
    exclude:
      - '../../src/DependencyInjection/'
      - '../../src/Entity/'
      - '../../src/Kernel.php'
